[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font Ret"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Ret"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Ret"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Ret"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
